### ISSUE TITLE
ValueError in pysift when running notebook

### ISSUE THREAD

**Issue by bobmoff** [adumrewal/SIFTImageSimilarity#1]
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The error is in pysift.py on row 134:
```python
if abs(center_pixel_value) > threshold:
```

<img width="1269" alt="Screenshot 2020-06-23 at 10 50 58" src="https://user-images.githubusercontent.com/1033236/85382621-6e850580-b53f-11ea-9560-1dabe0969157.png">

Looks like center_pixel_value is a ndarray with 3 floats. Not sure what the correct fix would be. All? Any? .. Or is there something else wrong perhaps ?

macOS 10.15.5
Python 3.7.5

**Comment by adumrewal** [comment]
Hi @bobmoff , did you convert your image to grayScale using `cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)` ?

**Comment by bobmoff** [comment]
ahh. thanks. i was trying to take a shortcut and missed that part.

now i have another question. :)

findScaleSpaceExtrema in pysift takes 102 seconds for me to run. is this normal ?

**Comment by adumrewal** [comment]
Yeah, if you look at the code, we have for loops everywhere which makes it highly inefficient. This can be improved a lot by writing an efficient code and utilising the parallel process and some simple techniques of caching. I might take this work up soon, not sure about this though.
I guess, this can easily be improved to somewhere better than 1 second.

**Comment by bobmoff** [comment]
ok. thanks for the fast replies. i might try and use opencvs sift implementation instead, if possible. have you tried ?

**Comment by adumrewal** [comment]
Yeah, you can definitely use opencv's internal sift library, it is very well optimised.
The only change you need to make is, instead of `pysift.computeKeypointsAndDescriptors(image)` you can use `cv2.SIFT_create()`.

**Comment by adumrewal** [comment]
@bobmoff I have updated the repo with provision for using either opencv's sift or custom sift implementation.

**Comment by bobmoff** [comment]
Oh, thats great! Thanks!
